### ISSUE TITLE
How to set round corners only to the left-top and right-top corners?

### ISSUE THREAD

**Issue by dosymbaev** [Navideck/TDRoundedNavigationBar#1]

**Comment by fotiDim** [comment]
@dosymbaev sorry for the delay. For some reason GitHub did not notify me. I have uploaded a new version. Please update and then you can do something like this in your View Controller:

```
guard let roundedBar = navigationController?.navigationBar as? TDRoundedNavigationBar else {return}
roundedBar.corners = [UIRectCorner.bottomLeft, UIRectCorner.bottomRight]
```

Closing the issue and if you have any problem we can reopen it.
